# v2 syntax
version: "2"

services:
  # MySQL
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./storage/app/mysql:/var/lib/mysql
    ports:
      - "3312:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mvc
      - MYSQL_DATABASE=mvc
      - MYSQL_USER=mvc
      - MYSQL_PASSWORD=mvc

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8006:8006"
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: mvc
      MYSQL_PASSWORD: mvc
      MYSQL_ROOT_PASSWORD: mvc

  # PHP (with NGINX)
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
