<aside>
  <ul id="slide-out" class="side-nav fixed">
    <li>
      <div class="user-view">
        <div class="background">
          <img src="http://lorempixel.com/output/nature-q-c-640-480-3.jpg">
        </div>
        <a href="#!user"><img class="circle" src="https://api.adorable.io/avatars/285/abott@adorable.png"></a>
        <a href="#!name"><span class="white-text name">John Doe</span></a>
        <a href="#!email"><span class="white-text email">johndoe@email.com</span></a>
      </div>
    </li>
    <li><a href="<?php route("home") ?>" class="waves-effect"><i class="material-icons">home</i>Home</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader">Subgroup</a></li>
    <li><a class="waves-effect" href="https://github.com/henriquecaraujo" target="_blank"><i class="material-icons">group</i>/henriquecaraujo</a></li>
  </ul>
</aside>
